server:
  port: 8080

#logging:
#  level:
#    root: DEBUG

security:
  basic:
    enabled: false

#serviceEndpoint: http://localhost:8081
serviceEndpoint: //billing
#serviceEndpoint: http://billing-undwindling-prefect.apps.cumuluslabs.io
